services:
  wan-ip-sync:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - DOCKER_REGISTRY_MIRROR=https://mirror.ccs.tencentyun.com
    container_name: wan-ip-sync
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - type: bind
        source: /mnt/d/01_docker/wan-ip-sync/config/config.yaml
        target: /app/config/config.yaml
        read_only: true
      - type: bind
        source: /mnt/d/01_docker/wan-ip-sync/data
        target: /app/data
      - type: bind
        source: /mnt/d/01_docker/wan-ip-sync/logs
        target: /app/logs
    working_dir: /app/src
    networks:
      - wan-ip-sync-network

networks:
  wan-ip-sync-network:
    driver: bridge
