services:
  wan-ip-sync:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - DOCKER_REGISTRY_MIRROR=https://mirror.ccs.tencentyun.com
    container_name: wan-ip-sync
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - type: bind
        source: ${CONFIG_PATH:-./config}
        target: /app/config
        read_only: true
      - type: bind
        source: ${DATA_PATH:-./data}
        target: /app/data
      - type: bind
        source: ${LOGS_PATH:-./logs}
        target: /app/logs
    working_dir: /app
    networks:
      - wan-ip-sync-network

networks:
  wan-ip-sync-network:
    driver: bridge
